# .travis.yml
language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database truegm_test'
